server:
  shutdown: graceful
management:
  server:
    port: 8081
spring:
  main:
    banner-mode: off
  kafka:
    producer:
      bootstrap-servers:
        - localhost:19092
        - localhost:29092
        - localhost:39092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      ack: all
      properties:
        partitioner.class: com.github.jiantailang.kafka.adapters.publisher.AvoidOfflinePartitioner
        spring.json.add.type.headers: false
    consumer:
      bootstrap-servers:
        - localhost:19092
        - localhost:29092
        - localhost:39092
      group-id: practical-kafka
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      isolation-level: read_committed
      max-poll-records: 1
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.StickyAssignor
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        #spring.deserializer.value.function: ? implements Function<FailedDeserializationInfo, T>
        spring.json.value.default.type: com.github.jiantailang.kafka.adapters.subscriber.Message
        spring.json.trusted.packages: com.github.jiantailang.kafka.adapters.subscriber
